### ISSUE TITLE
Documentation out of date: TimeSeries/BaseBar

### ISSUE THREAD

**Issue by toriacht** [ta4j/ta4j#520]
Hi,

The [docs](https://ta4j.github.io/ta4j-wiki/Time-series-and-bars.html) and examples  all refer to `TimeSeries` even though the code is updated to `BaseBar `since [0.13](https://github.com/ta4j/ta4j/blob/master/CHANGELOG.md) .

This should have been updated as part  of whatever ticket updated the code

**Comment by FPB-Indicators** [comment]
I agree, you have to update the documentation. It could be frustrating for new people who want to use TA4J, or those who pass from 0.12 to 0.13 (BTW I hope the code will not change a lot for TimeSeries, since I use custom implementation in few places on my application 😅)

**Comment by team172011** [comment]
done

**Comment by milczarekIT** [comment]
Hi @team172011,
I see you closed this issue, but I still see the old documentation: https://ta4j.github.io/ta4j-wiki/Time-series-and-bars.html ... with TimeSeries
